name: contionuos integration
on:
    pull_request:
      branches:
        - main
jobs:
  CI-job:
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |
            echo "This is pull-request"
            
