name: contionuos integration
on:
  workflow_dispatch
jobs:
  CI-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: sample
        run: |
            echo "component - ${{ vars.component }}" 
            echo "component - ${{ secrets.comp }}" > /tmp/1
            echo "--------"
            cat /tmp/1
            
