name: contionuos integration
on: [workflow_dispatch]
jobs:
  docker:
    environment: dev
    uses: RoboShop1/github-reusable/.github/workflows/docker-ci.yaml@main
    with:
      component_name: ${{ github.repository }}
    secrets: inherit

